### ISSUE TITLE
index.android.bundle in react native  70.4

### ISSUE THREAD

**Issue by alirezarastegarfard** [tapsellorg/TapsellPlusSDK-ReactNativeSample#20]
[Unable to load script.Make sure you are either running a Metro server or that your bundle 'index.android.bundle' is packaged correctly for release](https://stackoverflow.com/questions/55441230/unable-to-load-script-make-sure-you-are-either-running-a-metro-server-or-that-yo)

**Comment by MortezaNedaei** [comment]
It is fixed in `2.1.8` and tested with `0.71.6`. Please refer to sample application.
